import { injectable, inject } from 'tsyringe';
import {
  IReciboService,
  ReciboCalculationInput,
  ReciboCalculationResult,
  IGastoCondominioRepository,
  IPropiedadRepository,
  IReciboMensualRepository,
  IReciboMensual,
} from '@abitia/core';
import { ILedgerService } from '@abitia/core';

@injectable()
export class ReciboService implements IReciboService {
  constructor(
    @inject('IGastoCondominioRepository') private gastoRepo: IGastoCondominioRepository,
    @inject('IPropiedadRepository') private propiedadRepo: IPropiedadRepository,
    @inject('IReciboMensualRepository') private reciboRepo: IReciboMensualRepository,
    @inject('ILedgerService') private ledgerService: ILedgerService,
  ) {}

  calculateRecibo(input: ReciboCalculationInput): ReciboCalculationResult {
    const montoGastoComun = input.gastoComunTotal * input.alicuota;
    const montoGastoNoComun = input.gastosNoComunes;
    const montoFondoReserva = 0.00;
    const saldoAnteriorPendiente = input.saldoAnteriorPendiente;

    const totalAPagar = montoGastoComun + montoGastoNoComun + montoFondoReserva + saldoAnteriorPendiente;

    return {
      montoGastoComun: Math.round(montoGastoComun * 100) / 100,
      montoGastoNoComun: Math.round(montoGastoNoComun * 100) / 100,
      montoFondoReserva: Math.round(montoFondoReserva * 100) / 100,
      saldoAnteriorPendiente: Math.round(saldoAnteriorPendiente * 100) / 100,
      totalAPagar: Math.round(totalAPagar * 100) / 100,
    };
  }

  async emitirRecibosPeriodo(
    idCondominio: number,
    periodo: string,
    fechaVencimiento: Date,
  ): Promise<void> {
    const propiedades = await this.propiedadRepo.findAllByCondominio(idCondominio);
    const propiedadesActivas = propiedades.filter(p => p.Estatus === 1);
    if (propiedadesActivas.length === 0) return;

    const gastoComunTotal = await this.gastoRepo.sumGastoComunByPeriod(idCondominio, periodo);

    const fechaEmision = new Date();

    const recibos: Omit<IReciboMensual, 'IdRecibo'>[] = [];

    for (const propiedad of propiedadesActivas) {
      const gastosNoComunes = await this.getGastosNoComunes(idCondominio, periodo, propiedad.IdPropiedad);
      const saldoAnterior = await this.reciboRepo.getSaldoPendiente(idCondominio, propiedad.IdPropiedad);

      const calculo = this.calculateRecibo({
        idPropiedad: propiedad.IdPropiedad,
        alicuota: Number(propiedad.Alicuota),
        gastoComunTotal,
        gastosNoComunes,
        saldoAnteriorPendiente: saldoAnterior,
      });

      recibos.push({
        IdPropiedad: propiedad.IdPropiedad,
        Periodicidad_MesAnio: periodo,
        Fecha_Emision: fechaEmision,
        Fecha_Vencimiento: fechaVencimiento,
        Monto_Gasto_Comun: calculo.montoGastoComun,
        Monto_Gasto_NoComun: calculo.montoGastoNoComun,
        Monto_Fondo_Reserva: calculo.montoFondoReserva,
        Saldo_Anterior_Pendiente: calculo.saldoAnteriorPendiente,
        Total_A_Pagar: calculo.totalAPagar,
        Estatus_Pago: 0,
      });
    }

    await this.reciboRepo.createBatch(recibos);

    for (let i = 0; i < propiedadesActivas.length; i++) {
      const propiedad = propiedadesActivas[i];
      const recibo = recibos[i];
      const descripcion = `Recibo ${periodo} - ${propiedad.Codigo_Nro}`;

      // The recibo ID is generated by the DB; we need to link it in the ledger.
      // For local-first, IDs are assigned in sequence. For MySQL, we trust the batch IDs.
      await this.ledgerService.registrarReciboEmitido(
        idCondominio,
        propiedad.IdPropiedad,
        0, // Will be resolved by the repository
        descripcion,
        recibo.Total_A_Pagar,
      );
    }
  }

  private async getGastosNoComunes(
    idCondominio: number,
    periodo: string,
    _idPropiedad: number,
  ): Promise<number> {
    const gastos = await this.gastoRepo.findAllByPeriod(idCondominio, periodo);
    return gastos
      .filter(g => g.Tipo_Gasto === 2)
      .reduce((sum, g) => sum + Number(g.Monto), 0);
  }
}
